version: '3.8'
services:
  dagster:
    build:
      context: .
    container_name: dagster
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./buy_box_gcp_1:/app/buy_box_gcp_1  # Mount the DBT project folder
    environment:
      DAGSTER_HOME: /app/gcp_dagster
    command: ["dagit", "-h", "0.0.0.0", "-p", "3000"]
